// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lstwrlealjkcleairkbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzdHdybGVhbGprY2xlYWlya2JlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0ODU3NzUsImV4cCI6MjA3MzA2MTc3NX0.1CQm5ofgNnnPzx55Wa2eAdMUwdjobJXN1N6tAr5WMf8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});